
// Objective-C API for talking to the following Go packages
//
//	github.com/StarburstComputing/engine-go/mobile
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Mobile_FRAMEWORK_H__
#define __Mobile_FRAMEWORK_H__

#include "StarburstEngineMobile.objc.h"
#include "Universe.objc.h"

#endif
